//
//  key + Value .swift
//  KolYomAyaApp
//
//  Created by Islam Abotaleb on 7/25/20.
//  Copyright © 2020 Islam Abotaleb. All rights reserved.
//

import Foundation
extension Array {

    func filterDuplicates( includeElement: (_ lhs:Element,_ rhs:Element) -> Bool) -> [Element]{
        var results = [Element]()

        forEach { (element) in
            let existingElements = results.filter {
                return includeElement(element, $0)
            }
            if existingElements.count == 0 {
                results.append(element)
            }
        }

        return results
    }
}
class KeyAndValue {
    
    static var SURA_NAME = [(name: String, id: String)]()
    static var SURA_NUMBER = [(name: String, id: String)]()
    static func getSura_Name() {
        SURA_NAME.append(("الفاتحة", "001"))
        SURA_NAME.append(("البقرة","002"))
        SURA_NAME.append(("آل عمران","003"))
        SURA_NAME.append(("النساء","004"))
        SURA_NAME.append(("المائدة","005"))
        SURA_NAME.append(("الأنعام","006"))
        SURA_NAME.append(("الأعراف","007"))
        SURA_NAME.append(("الأنفال","008"))
        SURA_NAME.append(("التوبة","009"))
        SURA_NAME.append(("يونس","010"))
        SURA_NAME.append(("هود","011"))
        SURA_NAME.append(("يوسف","012"))
        SURA_NAME.append(("الرعد","013"))
        SURA_NAME.append(("إبراهيم","014"))
        SURA_NAME.append(("الحجر","015"))
        SURA_NAME.append(("النحل","016"))
        SURA_NAME.append(("الإسراء","017"))
        SURA_NAME.append(("الكهف","018"))
        SURA_NAME.append(("مريم","019"))
        SURA_NAME.append(("طه","020"))
        SURA_NAME.append(("الأنبياء","021"))
        SURA_NAME.append(("الحج","022"))
        SURA_NAME.append(("المؤمنون","023"))
        SURA_NAME.append(("النور","024"))
        SURA_NAME.append(("الفرقان","025"))
        SURA_NAME.append(("الشعراء","026"))
        SURA_NAME.append(("النمل","027"))
        SURA_NAME.append(("القصص","028"))
        SURA_NAME.append(("العنكبوت","029"))
        SURA_NAME.append(("الروم","030"))
        SURA_NAME.append(("لقمان","031"))
        SURA_NAME.append(("السجدة","032"))
        SURA_NAME.append(("الأحزاب","033"))
        SURA_NAME.append(("سبإ","034"))
        SURA_NAME.append(("فاطر","035"))
        SURA_NAME.append(("يس","036"))
        SURA_NAME.append(("الصافات","037"))
        SURA_NAME.append(("ص","038"))
        SURA_NAME.append(("الزمر","039"))
        SURA_NAME.append(("غافر","040"))
        SURA_NAME.append(("فصلت","041"))
        SURA_NAME.append(("الشورى","042"))
        SURA_NAME.append(("الزخرف","043"))
        SURA_NAME.append(("الدخان","044"))
        SURA_NAME.append(("الجاثية","045"))
        SURA_NAME.append(("الأحقاف","046"))
        SURA_NAME.append(("محمد","047"))
        SURA_NAME.append(("الفتح","048"))
        SURA_NAME.append(("الحجرات","049"))
        SURA_NAME.append(("ق","050"))
        SURA_NAME.append(("الذاريات","051"))
        SURA_NAME.append(("الطور","052"))
        SURA_NAME.append(("النجم","053"))
        SURA_NAME.append(("القمر","054"))
        SURA_NAME.append(("الرحمن","055"))
        SURA_NAME.append(("الواقعة","056"))
        SURA_NAME.append(("الحديد","057"))
        SURA_NAME.append(("المجادلة","058"))
        SURA_NAME.append(("الحشر","059"))
        SURA_NAME.append(("الممتحنة","060"))
        SURA_NAME.append(("الصف","061"))
        SURA_NAME.append(("الجمعة","062"))
        SURA_NAME.append(("المنافقون","063"))
        SURA_NAME.append(("التغابن","064"))
        SURA_NAME.append(("الطلاق","065"))
        SURA_NAME.append(("التحريم","066"))
        SURA_NAME.append(("الملك","067"))
        SURA_NAME.append(("القلم","068"))
        SURA_NAME.append(("الحاقة","069"))
        SURA_NAME.append(("المعارج","070"))
        SURA_NAME.append(("نوح","071"))
        SURA_NAME.append(("الجن","072"))
        SURA_NAME.append(("المزمل","073"))
        SURA_NAME.append(("المدثر","074"))
        SURA_NAME.append(("القيامة","075"))
        SURA_NAME.append(("الانسان","076"))
        SURA_NAME.append(("المرسلات","077"))
        SURA_NAME.append(("النبإ","078"))
        SURA_NAME.append(("النازعات","079"))
        SURA_NAME.append(("عبس","080"))
        SURA_NAME.append(("التكوير","081"))
        SURA_NAME.append(("الإنفطار","082"))
        SURA_NAME.append(("المطففين","083"))
        SURA_NAME.append(("الإنشقاق","084"))
        SURA_NAME.append(("البروج","085"))
        SURA_NAME.append(("الطارق","086"))
        SURA_NAME.append(("الأعلى","087"))
        SURA_NAME.append(("الغاشية","088"))
        SURA_NAME.append(("الفجر","089"))
        SURA_NAME.append(("البلد","090"))
        SURA_NAME.append(("الشمس","091"))
        SURA_NAME.append(("الليل","092"))
        SURA_NAME.append(("الضحى","093"))
        SURA_NAME.append(("الشرح","094"))
        SURA_NAME.append(("التين","095"))
        SURA_NAME.append(("العلق","096"))
        SURA_NAME.append(("القدر","097"))
        SURA_NAME.append(("البينة","098"))
        SURA_NAME.append(("الزلزلة","099"))
        SURA_NAME.append(("العاديات","100"))
        SURA_NAME.append(("القارعة","101"))
        SURA_NAME.append(("التكاثر","102"))
        SURA_NAME.append(("العصر","103"))
        SURA_NAME.append(("الهمزة","104"))
        SURA_NAME.append(("الفيل","105"))
        SURA_NAME.append(("قريش","106"))
        SURA_NAME.append(("الماعون","107"))
        SURA_NAME.append(("الكوثر","108"))
        SURA_NAME.append(("الكافرون","109"))
        SURA_NAME.append(("النصر","110"))
        SURA_NAME.append(("المسد","111"))
        SURA_NAME.append(("الإخلاص","112"))
        SURA_NAME.append(("الفلق","113"))
        SURA_NAME.append(("الناس","114"))
       
    }
    static func getSura_Number() {
        SURA_NUMBER.append(("الفاتحة", "001"))
        SURA_NUMBER.append(("البقرة","002"))
        SURA_NUMBER.append(("آل عمران","003"))
        SURA_NUMBER.append(("النساء","004"))
        SURA_NUMBER.append(("المائدة","005"))
        SURA_NUMBER.append(("الأنعام","006"))
        SURA_NUMBER.append(("الأعراف","007"))
        SURA_NUMBER.append(("الأنفال","008"))
        SURA_NUMBER.append(("التوبة","009"))
        SURA_NUMBER.append(("يونس","010"))
        SURA_NUMBER.append(("هود","011"))
        SURA_NUMBER.append(("يوسف","012"))
        SURA_NUMBER.append(("الرعد","013"))
        SURA_NUMBER.append(("إبراهيم","014"))
        SURA_NUMBER.append(("الحجر","015"))
        SURA_NUMBER.append(("النحل","016"))
        SURA_NUMBER.append(("الإسراء","017"))
        SURA_NUMBER.append(("الكهف","018"))
        SURA_NUMBER.append(("مريم","019"))
        SURA_NUMBER.append(("طه","020"))
        SURA_NUMBER.append(("الأنبياء","021"))
        SURA_NUMBER.append(("الحج","022"))
        SURA_NUMBER.append(("المؤمنون","023"))
        SURA_NUMBER.append(("النور","024"))
        SURA_NUMBER.append(("الفرقان","025"))
        SURA_NUMBER.append(("الشعراء","026"))
        SURA_NUMBER.append(("النمل","027"))
        SURA_NUMBER.append(("القصص","028"))
        SURA_NUMBER.append(("العنكبوت","029"))
        SURA_NUMBER.append(("الروم","030"))
        SURA_NUMBER.append(("لقمان","031"))
        SURA_NUMBER.append(("السجدة","032"))
        SURA_NUMBER.append(("الأحزاب","033"))
        SURA_NUMBER.append(("سبإ","034"))
        SURA_NUMBER.append(("فاطر","035"))
        SURA_NUMBER.append(("يس","036"))
        SURA_NUMBER.append(("الصافات","037"))
        SURA_NUMBER.append(("ص","038"))
        SURA_NUMBER.append(("الزمر","039"))
        SURA_NUMBER.append(("غافر","040"))
        SURA_NUMBER.append(("فصلت","041"))
        SURA_NUMBER.append(("الشورى","042"))
        SURA_NUMBER.append(("الزخرف","043"))
        SURA_NUMBER.append(("الدخان","044"))
        SURA_NUMBER.append(("الجاثية","045"))
        SURA_NUMBER.append(("الأحقاف","046"))
        SURA_NUMBER.append(("محمد","047"))
        SURA_NUMBER.append(("الفتح","048"))
        SURA_NUMBER.append(("الحجرات","049"))
        SURA_NUMBER.append(("ق","050"))
        SURA_NUMBER.append(("الذاريات","051"))
        SURA_NUMBER.append(("الطور","052"))
        SURA_NUMBER.append(("النجم","053"))
        SURA_NUMBER.append(("القمر","054"))
        SURA_NUMBER.append(("الرحمن","055"))
        SURA_NUMBER.append(("الواقعة","056"))
        SURA_NUMBER.append(("الحديد","057"))
        SURA_NUMBER.append(("المجادلة","058"))
        SURA_NUMBER.append(("الحشر","059"))
        SURA_NUMBER.append(("الممتحنة","060"))
        SURA_NUMBER.append(("الصف","061"))
        SURA_NUMBER.append(("الجمعة","062"))
        SURA_NUMBER.append(("المنافقون","063"))
        SURA_NUMBER.append(("التغابن","064"))
        SURA_NUMBER.append(("الطلاق","065"))
        SURA_NUMBER.append(("التحريم","066"))
        SURA_NUMBER.append(("الملك","067"))
        SURA_NUMBER.append(("القلم","068"))
        SURA_NUMBER.append(("الحاقة","069"))
        SURA_NUMBER.append(("المعارج","070"))
        SURA_NUMBER.append(("نوح","071"))
        SURA_NUMBER.append(("الجن","072"))
        SURA_NUMBER.append(("المزمل","073"))
        SURA_NUMBER.append(("المدثر","074"))
        SURA_NUMBER.append(("القيامة","075"))
        SURA_NUMBER.append(("الانسان","076"))
        SURA_NUMBER.append(("المرسلات","077"))
        SURA_NUMBER.append(("النبإ","078"))
        SURA_NUMBER.append(("النازعات","079"))
        SURA_NUMBER.append(("عبس","080"))
        SURA_NUMBER.append(("التكوير","081"))
        SURA_NUMBER.append(("الإنفطار","082"))
        SURA_NUMBER.append(("المطففين","083"))
        SURA_NUMBER.append(("الإنشقاق","084"))
        SURA_NUMBER.append(("البروج","085"))
        SURA_NUMBER.append(("الطارق","086"))
        SURA_NUMBER.append(("الأعلى","087"))
        SURA_NUMBER.append(("الغاشية","088"))
        SURA_NUMBER.append(("الفجر","089"))
        SURA_NUMBER.append(("البلد","090"))
        SURA_NUMBER.append(("الشمس","091"))
        SURA_NUMBER.append(("الليل","092"))
        SURA_NUMBER.append(("الضحى","093"))
        SURA_NUMBER.append(("الشرح","094"))
        SURA_NUMBER.append(("التين","095"))
        SURA_NUMBER.append(("العلق","096"))
        SURA_NUMBER.append(("القدر","097"))
        SURA_NUMBER.append(("البينة","098"))
        SURA_NUMBER.append(("الزلزلة","099"))
        SURA_NUMBER.append(("العاديات","100"))
        SURA_NUMBER.append(("القارعة","101"))
        SURA_NUMBER.append(("التكاثر","102"))
        SURA_NUMBER.append(("العصر","103"))
        SURA_NUMBER.append(("الهمزة","104"))
        SURA_NUMBER.append(("الفيل","105"))
        SURA_NUMBER.append(("قريش","106"))
        SURA_NUMBER.append(("الماعون","107"))
        SURA_NUMBER.append(("الكوثر","108"))
        SURA_NUMBER.append(("الكافرون","109"))
        SURA_NUMBER.append(("النصر","110"))
        SURA_NUMBER.append(("المسد","111"))
        SURA_NUMBER.append(("الإخلاص","112"))
        SURA_NUMBER.append(("الفلق","113"))
        SURA_NUMBER.append(("الناس","114"))
    }
}
